const VIDEO_PROCESSING_STATUS = {
  PROCESSING: 'PROCESSING',
  UPLOADING: 'UPLOADING',
  ERROR: 'ERROR',
  DONE: 'DONE',
};

const SAVE_FOR_LATER = {
  BOOKS: 'books',
};

module.exports = {
  VIDEO_PROCESSING_STATUS,
  SAVE_FOR_LATER,
};
